### ISSUE TITLE
probleme connexion utilisateur

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#132]
bonjour,
j'ai un souci de connexion d'une utilisatrice qui a oublié son mot de passe. Quand elle redemande une réinitialisation de son mot de passe, cela met que le mail n'est pas valide. Dans la base de données utilisateurs, le mail est bien correct. La seule piste est qu'il y a trois comptes pour cette personne avec le même mail. 
Stéphanie

**Comment by osallou** [comment]
seems in code that code expect to find only 1 user for an email, else it takes "none".
Software do not know which account should be reset

If someone have multiple accounts, should have a different email per account.... (bug is it should be checked at creation).

**Comment by osallou** [comment]
I think you should "delete" additional accounts (if possible and expecting it really removes it from database), and eventually update user accounts to get expected access.

**Comment by sdutertre** [comment]
Unless I am mistaken, it is not possible for me to delete users. Can you delete ID 167 and 958. Normally only ID 956 will remain for this person. Thanks

**Comment by osallou** [comment]
I deactivated ids 167 and 958 rather than removing them to avoid possible issues (user id referenced in previous reservations etc...) and updated code to search only for active users. So "password forgotten" should find only 1 user for this person now and system *should* work. 

I made a try and this person should have received an email to reset her password now.
