### ISSUE TITLE
[coreconfigadmin] need for tests

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#351]
Need to test {host}/coreconfigadmin options

**Comment by osallou** [comment]
@gaetanHerve quid de cette issue?

**Comment by gaetanHerve** [comment]
Je ne sais pas justement, il faut que je jette un oeil

**Comment by gaetanHerve** [comment]
There are still coreconfig menus useless / not working

- [ ] Maintenance mode => admins don't have access either
- [x] Icons of the home page
- [ ] Deactivate users => to be tested
- [x] Home
- [ ] Connection page date => ok, but no carousel (we talked about removing it)
- [ ] Who can delete users => should be reserved to admins. No need for this menu I think
- [ ] Deactivate users => towhich email send notifications ? to be tested
- [ ] Module color => not working

**Comment by osallou** [comment]
maintenance mode is for superadmin , and should be needed

deactivate, there is (will be) a cron script to manage users not logged since X days. Space admins cannot (should not) deactivate a user, just remove from from space. Super admin can deactivate users.

delete user: super admin only in ALL cases
